name: Update Dependencies

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: "0 9 * * 1"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    name: Update flake inputs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/flakehub-cache-action@main

      - name: Update flake inputs
        run: |
          nix flake update --commit-lock-file

      - name: Check if updates were made
        id: check_updates
        run: |
          if git diff --quiet HEAD~1 HEAD -- flake.lock; then
            echo "has_updates=false" >> $GITHUB_OUTPUT
          else
            echo "has_updates=true" >> $GITHUB_OUTPUT
          fi

      - name: Test updated flake
        if: steps.check_updates.outputs.has_updates == 'true'
        run: |
          nix flake check --all-systems

      - name: Create Pull Request
        if: steps.check_updates.outputs.has_updates == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update flake inputs"
          title: "chore: automated flake input updates"
          body: |
            ## Automated Dependency Update

            This PR updates the flake inputs to their latest versions.

            ### Changes
            ```
            ${{ steps.diff.outputs.diff }}
            ```

            ### Checklist
            - [ ] All tests pass
            - [ ] No breaking changes detected
            - [ ] Ready to merge

            *This PR was created automatically by the update-deps workflow.*
          branch: update-flake-inputs
          delete-branch: true
          labels: |
            dependencies
            automated
